<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
	</array>
	<key>name</key>
	<string>mdTodo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^[ ]{0,3}([-])(?=\s)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.pending</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=\S)</string>
			<key>name</key>
			<string>markup.list.pending.mdtodo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[ ]{0,3}([+])(?=\s)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.completed</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=\S)</string>
			<key>name</key>
			<string>markup.list.completed.mdtodo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.markdown</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>anything between double asterisks</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bold.mdtodo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bold.mdtodo</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\B(\*\*)\S[^\*]+\S(\*\*)\B</string>
					<key>name</key>
					<string>markup.bold.mdtodo</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>anything between single asterisks</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.mdtodo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.mdtodo</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\*)\b[^\*]*\b(\*)</string>
					<key>name</key>
					<string>markup.italic.mdtodo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)\@(?!today|done)[\w\d\-!?]+\s?</string>
					<key>name</key>
					<string>meta.tag.mdtodo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)\@today\s?</string>
					<key>name</key>
					<string>meta.tag.mdtodo.today</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)\@done \([\d\.:\-/ ].+\)\s?</string>
					<key>name</key>
					<string>meta.tag.mdtodo.completed</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.markdown.todo</string>
	<key>uuid</key>
	<string>8fj2g29c-04ef-4330-9a6b-9b99aae1c418</string>
</dict>
</plist>
